config/routes.rb
Rails.application.routes.draw do
  resources :sizes, :tags, :pictures, :promos, :statics, :carts
  devise_for :users

  resources :charges do
    collection do 
      get 'cart', to: 'charges#cart', as: :cart
      get 'oxxo', to: 'charges#oxxo', as: :oxxo 
      get 'show/:id', to: 'charges#show_charge', as: :show 
      post 'oxxo/pay', to: 'charges#oxxo_create', as: :oxxo_create
    end

    member do
      put 'send_number'
    end
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  get "linea/:id", to: 'user_admin#index', as: :user_profile
  get "linea/:id/ventas", to: 'user_admin#ventas', as: :user_ventas

  get "admin" => 'admin#index'
  get "admin/charges" => 'charges#index'
  get "admin/statics" => 'statics#index'
  get "admin/promos" => 'promos#index'
  get "admin/users" => 'admin#users'
  get "admin/tags" => 'tags#index'
  get "admin/sizes" => 'sizes#index'

  get "admin/users/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/users/:id" => 'admin#destroy_user', as: :user_delete
  patch "admin/users/:id" => 'admin#update'
  put "admin/users/:id" => 'admin#update', as: :user_edit_s

  get "admin/users/new" => 'admin#new', as: :user_new
  post "admin/users" => 'admin#create', as: :user_create

  get "products", to: 'posts#index', as: :products
  get "products/:id", to: 'posts#show', as: :product

  get "women", to: 'store#women', as: :women
  get "men", to: 'store#men', as: :men

  resources :posts do
    resource :like, module: :posts
  end

  get 'tag/:tag', to: 'posts#index', as: :tag_find

  root 'store#index'

  
  

end

app/views/admin/_admin_nav.html.erb
<div class="admin-nav">
	<ul class="side-nav">
		<li data-tooltip title="Inicio" class="logo-home"><%= link_to image_tag('logoz.svg'), root_path %></li>

		<li data-tooltip title="Productos" class="<%= 'active' if current_page?(admin_path) %>">
			<a href="/admin">
				<%= image_tag 'icons/square.svg' %>	
			</a>
		</li>
		<% if can? :update, Charge %>
			<li data-tooltip title="Cargos" class="<%= 'active' if current_page?(admin_charges_path) %>">
				<a href="/admin/charges">
					<%= image_tag 'icons/money.svg' %>	
				</a>
			</li>
		<% end %>
		<% if can? :manage, Static %>
			<li title="Páginas" class="<%= 'active' if current_page?(admin_statics_path) %>">
				<a href="/admin/statics">
					<%= image_tag 'icons/multimedia.svg' %>	
				</a>
			</li>
		<% end %>

		<% if can? :manage, Promo%>
			<li title="Promociones" class=" <%= 'active' if current_page?(admin_promos_path) %>">
				<a href="/admin/promos">
					<%= image_tag 'icons/sign.svg' %>	
				</a>
			</li>
		<% end %>
		<% if can? :manage, Tag %>
			<li title="Tags" class="<%= 'active' if current_page?(admin_tags_path) %>">
				<a href="<%= admin_tags_path %>">
					<%= image_tag 'icons/tag.svg' %>	
				</a>
			</li>
		<% end %>
		<% if can? :manage, Size %>
			<li title="Medidas" class="<%= 'active' if current_page?(admin_sizes_path) %>">
				<a href="<%= admin_sizes_path %>">
					<%= image_tag 'icons/size.svg' %>	
				</a>
			</li>
		<% end %>
		<% if can? :manage, User %>
			<li title="Usuarios" class="<%= 'active' if current_page?(admin_users_path) %>">
				<a href="/admin/users">
					<%= image_tag 'icons/people11.svg' %>	
				</a>
			</li>
		<% end %>
		<li>
			<%= link_to "mi perfil", user_profile_path(current_user), class: "link-user" %>
		</li>
		<li>
			<%= link_to "Salir", destroy_user_session_path, method: :delete %>
		</li>
	</ul>
</div>

app/views/admin/_charts.html.erb
<div class="row" style="padding-bottom: 2rem">
	<div style="width:50%">
		<canvas id="line_chart" height="450" width="600"></canvas>
	</div>
</div>


<script>
	$(function () {
		var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
		var lineChartData = {
			labels : ["En","Feb","Mar","Abr","May","Jun","Jul","Ag","Sept","Oct","Nov","Dic"],
			datasets : [
				{
					label: "2015",
					fillColor : "rgba(151,187,205,0.2)",
					strokeColor : "rgba(151,187,205,1)",
					pointColor : "rgba(151,187,205,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(220,220,220,1)",
					data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(), randomScalingFactor(),randomScalingFactor(), randomScalingFactor(),randomScalingFactor(), randomScalingFactor()]
				}
				// {
				// 	label: "My Second dataset",
				// 	fillColor : "rgba(151,187,205,0.2)",
				// 	strokeColor : "rgba(151,187,205,1)",
				// 	pointColor : "rgba(151,187,205,1)",
				// 	pointStrokeColor : "#fff",
				// 	pointHighlightFill : "#fff",
				// 	pointHighlightStroke : "rgba(151,187,205,1)",
				// 	data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
				// }
			]

		}


		var ctx = $('#line_chart').get(0).getContext("2d");
		var myChart = new Chart(ctx).Line(lineChartData, {
			responsive: true
		});
	});
	
</script>

app/views/admin/_form.html.erb
<%= render 'admin_nav' %>

<section class="content">
	<br>
	<div class="hu">
		<p><%= @user.role %></p>
	</div>

	<%= form_for(@user, url: user_edit_s_path) do |f| %>

		<table>
			<thead>
				<tr>
					<th></th>
					<th>nombre</th>
					<th>email</th>
					<th>twitter</th>
					<th>ultima ip</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<% if @user.avatar.exists? %>
						<td><%= image_tag(@user.avatar.url(:small), size: "50") %></td>
					<% else %>
						<td><%= image_tag('default.png', size: "50") %></td>
					<% end %>
					<td>
						<%= link_to @user.name, user_profile_path(@user) %>
					</td>
					<td>
						<a href="mailto:<%= @user.email %>"><%= @user.email %></a>
					</td>
					<% if not @user.twitter.blank? %>
						<td>
							<%= link_to @user.twitter, "https://twitter.com/#{@user.twitter}" %>
						</td>
					<% else %>
						<td>n/a</td>
					<% end %>
					<td><%= @user.last_sign_in_ip %></td>
					<td>
						<%= f.radio_button :role, :default %>
						<%= f.label :default %>
						<%= f.radio_button :role, :editor %>
						<%= f.label :editor %>
						<%= f.radio_button :role, :artist %>
						<%= f.label :artist %>
					</td>

				</tr>
			</tbody>
		</table>

	<%= f.button "actualizar", class: "button tiny green large-12" %>
	<% end %>

</section>

app/views/admin/_new_thing.html.erb
<a href="<%= url %>" title="<%= title %>">
		<div class="new-thing">+</div>
	</a>

app/views/admin/edit.html.erb
<%= render 'form' %>

app/views/admin/index.html.erb
<%= render 'admin_nav' %>

<section class="content">

	<br>
	<div class="large-6 columns">
		<div class="hu">
			<p><%= @posts.count %></p>
			<h2>Productos</h2>
		</div>
	</div>
	<div class="large-6 columns">
		<div class="hu">
			<p><%= @stock %></p>
			<h2>Inventario</h2>
		</div>
	</div>
	<div class="large-12 columns">
		<div class="hu">
			<p class="text-red"><%= @zero_stock %></p>
			<h2 class="text-red">Productos sin inventario</h2>
		</div>
	</div>



		<% if can? :manage, Post %>
			<%= render 'new_thing', url: new_post_path, title: "Producto nuevo" %>
		<% end %>

		<%= search_form_for(@q, url: admin_path, html:{class: "large-12"}) do |f| %>
			<%= f.search_field :title_or_sku_cont, {placeholder: "buscar producto", class: "radius"} %>
		<% end %>

	<table>
		<thead>
			<tr>
				<th class="la-10"><%= sort_link @q, :created_at, 'Fecha' %></th>
				<th></th>
				<th class="la-20">Titulo</th>
				<th class="la-10"><%= sort_link @q, :stock %></th>
				<th class="la-10"><%= sort_link @q, :user_name, 'Autor' %></th>
				<th class="la-10">Sku</th>
				<th class="la-10"><%= sort_link @q, :price, 'Precio' %></th>
				<th class=""><%= sort_link @q, :published, 'Publicado?' %></th>
				<th class="">Destacado?</th>
				<th class="">Edición</th>
			</tr>
		</thead>
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<td><%= local_time(post.created_at, '%b %e, %Y') %></td>
					<td>
						<% unless post.pictures.empty? %>
							<div class="th">
								<%= image_tag(post.pictures.first.image.url(:thumbnail), size: "50") %>
							</div>
						<% else %>
							<p>N/A</p>
						<% end %>
					</td>
					<td class="title"><%= link_to post.title, edit_post_path(post) %></td>

					<td><%= post.stock %></td>

					<% if post.user %>
						<td><%= post.user.name %></td>
					<% else %>
						<td>?</td>
					<% end %>

					<td><%= post.sku %></td>
					<td>$<%= post.price %></td>

					
					<td class="publicado">
						<% if post.published %>
							<i class="fa fa-check"></i>
						<% else %>
							<i class="fa fa-close"></i>
						<% end %>
					</td>
					<td class="publicado">
						<% if post.featured %>
							<i class="fa fa-star"></i>
						<% else %>
							<i calss="fa fa-star-o"></i>
						<% end %>
					</td>
					<td>
						<%= link_to "Eliminar", post, method: :delete, data: {confirm: "¿Estas seguro?"}, class: "" %>
					</td>
				</tr>
				<% post.variations.each do |v| %>
					<tr>
						<td></td>
						<td class="text-center">-</td>
						<td><%= v.size %></td>
						<% if v.stock < 11 %>
							<td class="text-red"><%= v.stock %></td>
						<% else %>
							<td class="text-green"><%= v.stock %></td>
						<% end %>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				<% end %>


			<% end %>
		</tbody>
	</table>

	<%= will_paginate @posts, page_links: false %>
</section>

app/views/admin/new.html.erb
<%= render 'admin_nav' %>

<section class="content">
	<br>
	<div class="hu">
		<p>Nuevo usuario</p>
	</div>

		<%= simple_form_for @user, url: user_create_path do |f| %>
			<div class="large-12 columns">
				<%= f.input :name, label: 'Nombre', class: "aoisdjoaij" %>
			</div>
			<div class="large-6 columns">
				<%= f.input :email %>
			</div>
			<div class="large-6 columns">
				<%= f.input :role, collection: User::Roles, label: 'Rol' %>
			</div>
			<div class="large-6 columns">
				<%= f.input :password, label: 'Contraseña' %>
			</div>
			<div class="large-6 columns">
				<%= f.input :password_confirmation, label: 'Confirmacion de contraseña' %>
			</div>

			<%= f.submit "guardar", class: "button tiny green large-12" %>
		<% end %>
		

</section>

app/views/admin/users.html.erb
<%= render 'admin_nav' %>
<section class="content">
	<br>
	<div class="hu">
		<p><%= @users.count %></p>
		<h2>Users</h2>
		<h2>Hola <%= current_user.name %> (<%= current_user.role %>)</h2>
	</div>
	<%= render 'new_thing', url: user_new_path, title: "nuevo usuario" %>

	<%= search_form_for(@st, url: admin_users_path, html:{class: "large-12"}) do |f| %>
    <%= f.search_field :name_or_twitter_or_email_or_role_cont, {placeholder: "buscar nombre, twitter, email o rol", class: "radius"} %>
  <% end %>
	<table>
		<thead>
			<tr>
				<th>id</th>
				<th><%= sort_link @st, :name, 'Nombre' %></th>
				<th>twitter</th>
				<th><%= sort_link @st, :email, 'Email' %></th>
				<th>current or last sign in IP</th>
				<th><%= sort_link @st, :role, "Rol" %></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<% if user == current_user %>
				<tr>
						<td><%= user.id %></td>
						<td><%= link_to "#{user.name}", user_profile_path(user) %></td>
						<td><a href="https://twitter.com/<%= user.twitter %>">@<%= user.twitter %></a></td>
						<td><a href="mailto:<%= user.email %>"><%= user.email %></a></td>
						<td><%= user.current_sign_in_ip %></td>
						<td><%= user.role %></td>
						<td>
							
						</td>
					</tr>
				<% else %>
					<tr>
						<td><%= user.id %></td>
						<td><%= link_to "#{user.name}", user_profile_path(user) %></td>
						<td><a href="https://twitter.com/<%= user.twitter %>">@<%= user.twitter %></a></td>
						<td><a href="mailto:<%= user.email %>"><%= user.email %></a></td>
						<td><%= user.current_sign_in_ip %></td>
						<td><%= user.role %></td>
						<td>
							<%= link_to "editar", user_edit_path(user) %> |
							<%= link_to "eliminar", user_delete_path(user), method: :delete, data: { confirm: "¿Estas seguro?"} %>
						</td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
<%= will_paginate @users, page_links: false %>

</section>