config/routes.rb
Rails.application.routes.draw do
  resources :sizes, :tags, :pictures, :promos, :statics, :carts
  devise_for :users

  resources :charges do
    collection do 
      get 'cart', to: 'charges#cart', as: :cart
      get 'oxxo', to: 'charges#oxxo', as: :oxxo 
      get 'show/:id', to: 'charges#show_charge', as: :show 
      post 'oxxo/pay', to: 'charges#oxxo_create', as: :oxxo_create
    end

    member do
      put 'send_number'
    end
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  get "linea/:id", to: 'user_admin#index', as: :user_profile
  get "linea/:id/ventas", to: 'user_admin#ventas', as: :user_ventas

  get "admin" => 'admin#index'
  get "admin/charges" => 'charges#index'
  get "admin/statics" => 'statics#index'
  get "admin/promos" => 'promos#index'
  get "admin/users" => 'admin#users'
  get "admin/tags" => 'tags#index'
  get "admin/sizes" => 'sizes#index'

  get "admin/users/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/users/:id" => 'admin#destroy_user', as: :user_delete
  patch "admin/users/:id" => 'admin#update'
  put "admin/users/:id" => 'admin#update', as: :user_edit_s

  get "admin/users/new" => 'admin#new', as: :user_new
  post "admin/users" => 'admin#create', as: :user_create

  get "products", to: 'posts#index', as: :products
  get "products/:id", to: 'posts#show', as: :product

  get "women", to: 'store#women', as: :women
  get "men", to: 'store#men', as: :men

  resources :posts do
    resource :like, module: :posts
  end

  get 'tag/:tag', to: 'posts#index', as: :tag_find

  root 'store#index'

  
  

end

app/views/shared/_alert.html.erb
<% if notice %>
  <div id="notice">
    <p><%= notice %></p>
  </div> 
<% end %>
<% if alert %>
    <div id="alert">
      <p><%= alert %></p>
    </div>
<% end %>

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= GOOGLE_ANALYTICS_ID %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_cart_box.html.erb
<% if @cart %>
	<ul class="dropdown" id="cart">
		<% if @cart.line_items.empty? %>
			<li>Carrito vacio</li>
		<% else %>
			<%= render 'line_items/line_item' %>
		<% end %>
	</ul>
<% end %>

app/views/shared/_disqus_count.html.erb
<script type="text/javascript">
	var disqus_shortname = '<%= DISQUS_SHORTNAME %>'; // required: replace example with your forum shortname

	$(document).on('page:load', function() { 

	    var s = document.createElement('script'); s.async = true;
	    s.type = 'text/javascript';
	    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
	    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
	}());

</script>

app/views/shared/_facebbok_sdk.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=1648950875340501";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_facebook_comments.html.erb
<div class="fb-comments" data-href="<%= url %>" data-numposts="15" data-width="100%"></div>

app/views/shared/_footer.html.erb
<footer>
	<div class="center text-center large-11 small-11 medium-11">

		<div class="f one">

				<% @pages.each do |page| %>
					<%= link_to page.title, static_path(page) %>
				<% end %>
				<p>© <%= Time.now.year %> <%= SITE_NAME %> Todos los derechos reservados.</p>
		</div>
		
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area" data-no-turbolink>
    <li class="name">
	    <%= link_to image_tag('logoz.svg'), root_path, class: "logo" %>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->

    <ul class="right">
    	<% if user_signed_in? %>
    		<% if can? :manage, Post %>
		      <li class="has-dropdown">
		        <a href="#" title="mi cuenta" >
              <div class="icon-user"></div>
            </a>
		        <ul class="dropdown">
		      		<li class=""><a href="<%= admin_path %>">Admin</a></li>
		          <li><a href="<%= user_profile_path(current_user) %>">Mis favoritos</a></li>
              <li><a href="<%= edit_user_registration_path %>">Mi perfil</a></li>
		          <li><%= link_to "salir", destroy_user_session_path, method: :delete %></li>
		        </ul>
		      </li>
		      <li class="cart-container">
		      	<a href="<%= cart_charges_path %>" title="ver carrito">
              <div class="icon-cart"></div>
            </a>
            <% if @cart %>
              <% unless @cart.line_items.count < 1 %>
                <div class="cart-count">
                  <%= @cart.line_items.count %>
                </div>
              <% end %>
            <% end %>
		      </li>
    		<% else %>
    			<li class="has-dropdown">
		        <a href="#" title="mi cuenta">
              <div class="icon-user"></div>
            </a>
		        <ul class="dropdown">
		          <li><a href="<%= user_profile_path(current_user) %>">Mis favoritos</a></li>
		          <li><a href="<%= edit_user_registration_path %>">Mi perfil</a></li>
		          <li><%= link_to "salir", destroy_user_session_path, method: :delete %></li>
		        </ul>
		      </li>
		      <li class="cart-container">
            <a href="<%= cart_charges_path %>" title="ver carrito">
              <div class="icon-cart"></div>
            </a>
            <% if @cart %>
              <% unless @cart.line_items.count < 1 %>
                <div class="cart-count">
                  <%= @cart.line_items.count %>
                </div>
              <% end %>
            <% end %>
          </li>
    		<% end %>



    	<% else %>
    		<li>
    			<%= link_to "Inicia sesión", new_user_session_path, class: "" %>
    		</li>
        <li>
          <%= link_to "Registro", new_user_registration_path %>
        </li>
    	<% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left" data-no-turbolink>
      <li><a href="<%= root_path %>">Inicio</a></li>
      <li class="has-dropdown">
      	<a href="#">Marcas</a>
      	<ul class="dropdown">
      		<li class="has-dropdown">
      			<a href="<%= men_path %>">Hombre</a>
      			<ul class="dropdown">
	      			<% Post.men.each do |category| %>
	      				<li><a href="<%= user_profile_path(category.user) %>"><%= category.user.name %></a></li>	
	      			<% end %>
      			</ul>
      		</li>
      		<li class="has-dropdown">
      			<a href="<%= women_path %>">Mujer</a>
      			<ul class="dropdown">
      			<% Post.women.each do |category| %>
      				<li><a href="<%= user_profile_path(category.user) %>"><%= category.user.name %></a></li>	
      			<% end %>
      			</ul>
      		</li>
      		
      	</ul>
      </li>
      <li class="has-form">
      	<%= search_form_for(@q, url: products_path, html:{class: "lp", id: "post_search"}) do |f| %>
	      	<div class="row collapse">
	      		<div class="large-12 small-12 columns">
							<%= f.search_field :title_or_sku_or_tags_name_or_user_name_cont, {placeholder: "buscar", class: ""} %>
	      		</div>
	      	</div>
				<% end %>
      </li>
    </ul>
  </section>
</nav>

app/views/shared/_menu_box.html.erb
<div class="menu-info">
	<div class="image-menu">
	</div>
	<div class="inner2">
		<div class="inner-content">
			<%= search_form_for(@q, url: products_path, html:{class: "sldkjfldkj", id: "post_search2"}) do |f| %>
				<%= f.search_field :title_or_sku_or_tags_name_cont, {placeholder: "buscar producto", class: "radius"} %>
			<% end %>

			<% if user_signed_in? %>
				<% if can? :manage, Post %>
					<a href="<%= root_path %>">
							<i class="fa fa-home inline"></i>
							<p class="inline">Inicio</p>
					</a>
					<a href="<%= admin_path %>">
							<i class="fa fa-sliders inline"></i>
							<p class="inline">Admin</p>
					</a>
					<a href="<%= products_path %>">
							<i class="fa fa-bolt inline"></i>
							<p class="inline">Todos los productos</p>
					</a>
					<a href="<%= user_profile_path(current_user) %>">
							<i class="fa fa-user inline"></i>
							<p class="inline">Perfil</p>
					</a>


						<%= link_to "Salir", destroy_user_session_path, method: :delete, class: "button tiny expand green2 radius" %>
					
				<% else %>

					<a href="<%= root_path %>">
							<i class="fa fa-home inline"></i>
							<p class="inline">Inicio</p>
					</a>
					<a href="<%= products_path %>">
							<i class="fa fa-bolt inline"></i>
							<p class="inline">Todos los productos</p>
					</a>
					<a href="<%= user_profile_path(current_user) %>">
							<i class="fa fa-user inline"></i>
							<p class="inline">Perfil</p>
					</a>

						<%= link_to "salir", destroy_user_session_path, method: :delete, class: "button tiny expand green2 radius" %>
				<% end %>
			<% else %>
				<a href="<%= root_path %>">
							<i class="fa fa-home inline"></i>
							<p class="inline">Inicio</p>
					</a>
					<a href="<%= products_path %>">
							<i class="fa fa-bolt inline"></i>
							<p class="inline">Todos los productos</p>
					</a>

				<%= link_to "Inicia sesión", new_user_session_path, class: "button tiny expand green2 radius" %>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_payment_form.html.erb
<%= form_for(@charge, url: charges_path, method: :post, html: {id: ''} ) do |f| %>

  <!-- <span class="card-errors"><%= flash[:error] if flash[:error]%></span> -->

  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title">
    <h1>Datos de envio</h1>
  </div>

  <div class="large-12 columns">
    <%= f.text_field :name, placeholder: "Nombre", maxlength: "20", class: "radius" %>
  </div>
  <div class="large-12 columns">
    <%= f.text_field :full_address, placeholder: "direccion", class: "radius" %>
  </div>
  
  <hr>


<!-- 
  <div class="title">
    <h1>Datos de envío</h1>
  </div>

  <div class="row">
    <div class="large-6 medium-6 small-12 columns">
      <input class="radius" type="text" data-conekta="card[name]" placeholder="Nombre del tarjetahabiente">
    </div>
    <div class="large-6 medium-6 small-12 columns">
      <input class="radius" type="text" data-conekta="card[number]" placeholder="Numero de tarjeta de crédito" value="4242424242424242" >
    </div>
  </div>

  <div class="row">
    <div class="large-4 medium-4 small-12 columns">
      <input class="radius" type="text" data-conekta="card[cvc]" placeholder="CVC" maxlength="3" >
    </div>
    <div class="large-4 medium-4 small-12 columns">
      <input class="radius" type="text" data-conekta="card[exp_month]" placeholder="Mes expiración (MM)" maxlength="2" >
    </div>
    <div class="large-4 medium-4 small-12 columns">
      <input class="radius" type="text" data-conekta="card[exp_year]" placeholder="Año expiración (AAAA)" maxlength="4">
    </div>
  </div>
 -->
  




  

  <%= f.submit "Comprar", class: "button green radius small expand" %>
<% end %>

app/views/shared/_scripts.html.erb
<script>
	$(function(){
		var button = $('.menu-info');
		var button2 = $('.cart-box');
		var image = $('.menu-info .image-menu');
		var image2 = $('.cart-box .image-cart');

		image2.click(function(){
			button2.toggleClass("oo");

			if (button2.hasClass("oo")) {
				$('main').click(function(){
					button2.removeClass("oo");
				});
			};
		});
		image.click(function(){
			button.toggleClass("kk");

			if (button.hasClass("kk")) {
				$('main').click(function(){
					button.removeClass("kk");
				});
			};
		});

	});

</script>