config/routes.rb
Rails.application.routes.draw do
  resources :sizes, :tags, :pictures, :promos, :statics, :carts
  devise_for :users

  resources :charges do
    collection do 
      get 'cart', to: 'charges#cart', as: :cart
      get 'oxxo', to: 'charges#oxxo', as: :oxxo 
      get 'show/:id', to: 'charges#show_charge', as: :show 
      post 'oxxo/pay', to: 'charges#oxxo_create', as: :oxxo_create
    end

    member do
      put 'send_number'
    end
  end

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  get "linea/:id", to: 'user_admin#index', as: :user_profile
  get "linea/:id/ventas", to: 'user_admin#ventas', as: :user_ventas

  get "admin" => 'admin#index'
  get "admin/charges" => 'charges#index'
  get "admin/statics" => 'statics#index'
  get "admin/promos" => 'promos#index'
  get "admin/users" => 'admin#users'
  get "admin/tags" => 'tags#index'
  get "admin/sizes" => 'sizes#index'

  get "admin/users/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/users/:id" => 'admin#destroy_user', as: :user_delete
  patch "admin/users/:id" => 'admin#update'
  put "admin/users/:id" => 'admin#update', as: :user_edit_s

  get "admin/users/new" => 'admin#new', as: :user_new
  post "admin/users" => 'admin#create', as: :user_create

  get "products", to: 'posts#index', as: :products
  get "products/:id", to: 'posts#show', as: :product

  get "women", to: 'store#women', as: :women
  get "men", to: 'store#men', as: :men

  resources :posts do
    resource :like, module: :posts
  end

  get 'tag/:tag', to: 'posts#index', as: :tag_find

  root 'store#index'

  
  

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy

	validates :name, :full_address, :phone_number, :country, :state, :city, :zip_code, :colonia, presence: true
  
  scope :default, -> {order('created_at desc')}
  # scope :charges_in_months, ->(number) {where(created_at: (Time.now - 1.month)..Time.now)}
  def self.charges_in_months(number)
  	where(created_at: (Time.now - number.month)..Time.now)
  end

	Stages = [['En proceso', :en_proceso], ['Pago recibido y listo para envio', :listo_para_envio], ['Enviado', :enviado]]

	def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
		  item.cart_id = nil
		  line_items << item 
	  end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :check_admin, only: [:index, :show]
  before_action :set_cart, only: [:new, :create, :cart, :oxxo, :oxxo_create]
  before_action :set_charge, only: [:show, :edit, :update, :destroy, :show_charge]




  # GET /charges
  # GET /charges.json
  def index
    @path = "charges"
    @body_class = "admin"

    @st = Charge.search(params[:q])
    @charges = @st.result(distinct: true).order(created_at: :desc).paginate(per_page: 50, page: params[:page])
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
    @path = "charges"
    @body_class = "admin"
  end

  # GET /charges/new
  def new

    if @cart.line_items.empty?
      redirect_to root_path, notice: 'Tu carrito está vacio...'
    else
      @body_class = "pay"
      @charge = Charge.new

      @ship_price = calculate_shipping_amount(total_items, "medium")
      @total_price = (@cart.total_price_cart + @ship_price)
    end
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    
    # redirect_to root_path if @cart.line_items.empty?

    ship_price = calculate_shipping_amount(total_items, "medium")

    total_pricec = (ship_price + @cart.total_price_cart) * 100
    total_pricecc = ship_price + @cart.total_price_cart

    order_sku = unique_id()

    begin
      charge = Conekta::Charge.create({
        amount: total_pricec.to_i,
        currency: "MXN",
        description: "Orden de la zapateria",
        reference_id: "#{order_sku}",
        card: params[:conektaTokenId],
        details: {
          name: params[:charge][:name],
          email: current_user.email,
          phone: params[:charge][:phone_number],
          billing_address: {
            company_name: "n/a",
            street1: params[:charge][:full_address],
            city: params[:charge][:city],
            state: params[:charge][:state],
            zip: params[:charge][:zip_code],
            phone: params[:charge][:phone_number],
            email: current_user.email
          }
        }
        #"tok_a4Ff0dD2xYZZq82d9"
      })
      # @charge = Charge.new(charge_params)
      @charge = Charge.new(
          user_id: current_user.id.to_i,
          name: params[:charge][:name],
          full_address: params[:charge][:full_address],
          colonia: params[:charge][:colonia],
          city: params[:charge][:city],
          country: params[:charge][:country],
          state: params[:charge][:state],
          zip_code: params[:charge][:zip_code],
          phone_number: params[:charge][:phone_number],
          livemode: charge.livemode,
          conekta_status: charge.status,
          amount: total_pricecc.to_i,
          conekta_id: order_sku,
          payment_type: "Tarjeta de credito",
          delivery_service: "DHL",
          currency: charge.currency
        )
      @charge.add_line_items_from_cart(@cart)

      if @charge.save
        @charge.line_items.each do |line_item|
          ## always variation exists
          variation = Variation.find_by(post_id: line_item.post.id, size: line_item.property).decrement(:stock, line_item.quantity)
          variation.save
        end


        

        @charge.stock_discounted = true
        @charge.save

        General.charge_paid(@charge).deliver
        General.charge_paid_admin(@charge).deliver
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        redirect_to show_charges_path(@charge)
      else
        redirect_to new_charge_path
      end

    rescue Conekta::ParameterValidationError => e
      #alguno de los parametros fueron invalidos
      puts e.message
    rescue Conekta::ProcessingError => e 
      # la tarjeta no pudo ser procesada, por ejemplo tarjeta declinada
      puts e.message
      redirect_to new_charge_path, alert: "Tarjeta no pudo ser procesada, la tarjeta fue declinada, intenta nuevamente o con otra tarjeta."
    rescue Conekta::Error => e
      #un error ocurrió que no sucede en el flujo normal de cobros como por ejemplo un auth_key incorrecto
      redirect_to new_charge_path, alert: "Tarjeta no pudo ser procesada, intenta nuevamente."  
      puts e.message
    
    end



  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update


    respond_to do |format|
      if (@charge.stock_discounted == false) and (params[:charge][:status] == "enviado")
        @charge.update(charge_params)

        @charge.line_items.each do |line_item|
          ## always variation exists
          variation = Variation.find_by(post_id: line_item.post.id, size: line_item.property).decrement(:stock, line_item.quantity)
          variation.save
        end

        @charge.stock_discounted = true
        @charge.save
        format.html { redirect_to @charge, notice: 'Charge updated!'}
        format.json { render :show, status: :ok, location: @charge }
      else
        @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge updated!'}
        format.json { render :show, status: :ok, location: @charge }
      end
    end

  end



  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was destroyed.' }
      format.json { head :no_content }
    end
  end


  # GET
  def cart
    if @cart.line_items.empty?
      redirect_to root_path, notice: 'Tu carrito esta vacio'
    else
      @body_class = "pay"
      @ship_price = calculate_shipping_amount(total_items, "medium")
    end
  end

  # GET
  def show_charge
    redirect_to root_path unless @charge.user.id == current_user.id
    @body_class = "show_charge"
  end

  # GET
  def oxxo
    redirect_to root_path if @cart.line_items.empty?

    @body_class = "pay"
    @charge = Charge.new

    @ship_price = calculate_shipping_amount(total_items, "medium")
    @total_price = (@cart.total_price_cart + @ship_price)

  end


  ## Payment with OXXO
  # POST
  def oxxo_create

    ship_price = calculate_shipping_amount(total_items, "medium")

    total_pricec = (ship_price + @cart.total_price_cart) * 100
    total_pricecc = ship_price + @cart.total_price_cart

    order_sku = unique_id()

    begin
      charge = Conekta::Charge.create({
        currency: "MXN",
        amount: total_pricec.to_i,
        description: "Orden de la zapateria",
        reference_id: "#{order_sku}",
        cash: {
          type: "oxxo"  
        },
        details: {
          name: params[:charge][:name],
          email: current_user.email,
          phone: params[:charge][:phone_number],
          billing_address: {
            company_name: "n/a",
            street1: params[:charge][:full_address],
            city: params[:charge][:city],
            state: params[:charge][:state],
            zip: params[:charge][:zip_code],
            phone: params[:charge][:phone_number],
            email: current_user.email
          }

        }
        #"tok_a4Ff0dD2xYZZq82d9"
      })
      # @charge = Charge.new(charge_params)
      @charge = Charge.new(
          user_id: current_user.id.to_i,
          name: params[:charge][:name],
          full_address: params[:charge][:full_address],
          colonia: params[:charge][:colonia],
          city: params[:charge][:city],
          country: params[:charge][:country],
          state: params[:charge][:state],
          zip_code: params[:charge][:zip_code],
          phone_number: params[:charge][:phone_number],
          livemode: charge.livemode,
          conekta_status: charge.status,
          amount: total_pricecc.to_i,
          conekta_id: order_sku,
          payment_type: "OXXO",
          payment_barcode: charge.payment_method.barcode,
          payment_bar_url: charge.payment_method.barcode_url,
          delivery_service: "DHL",
          currency: charge.currency
        )
      @charge.add_line_items_from_cart(@cart)
      
      if @charge.save
        General.oxxo_created(@charge).deliver
        General.oxxo_created_admin(@charge).deliver
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        # puts charge.payment_method.barcode_url
        redirect_to show_charges_path(@charge)
      else
        redirect_to oxxo_charges_path
      end
      
    rescue Conekta::ParameterValidationError => e
      #alguno de los parametros fueron invalidos
      puts e.message
    rescue Conekta::ProcessingError => e 
      # la tarjeta no pudo ser procesada
      puts e.message
    rescue Conekta::Error => e
      #un error ocurrió que no sucede en el flujo normal de cobros como por ejemplo un auth_key incorrecto
      redirect_to oxxo_charges_path, alert: "El cargo no pudo ser procesado"
      puts e.message
      
    end
    
  end

  def send_number
    @charge = Charge.find(params[:id])

    unless @charge.ship_number
      redirect_to charges_path, alert: "No hay numero de guia" 
    else
      General.shipped(@charge).deliver
      @charge.increment(:counter)
      @charge.save
      redirect_to @charge, notice: "Numero ha sido enviado!"
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    def total_items
      item_count = 0
      @cart.line_items.each do |item|
        item_count += item.quantity
      end
      item_count
    end

    def calculate_shipping_amount(items, size="medium")
      if size == "big"
        interval = 1.0
      elsif size == "medium"
        interval = 2.0
      elsif size == "small"
        interval = 3.0
      end

      return ((items/interval).ceil) * SHIP_PRICE 
    end

    def unique_id
      time = Time.new
      "#{time.min}#{time.hour}#{time.day}#{time.month}#{time.year}#{current_user.name.parameterize}"
      # "#{time.sec}#{time.min}#{time.hour}#{time.day}#{time.month}#{time.year}#{current_user.name.parameterize}"
    end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_cart_resume.html.erb
	<h1>Resumen de orden</h1>
		<table class="large-11 small-11 medium-11 center">
			<thead>
				<th></th>
				<th>Nombre</th>
				<th>P. Unitario</th>
				<th>Cantidad</th>
				<th>Detalles</th>
				<th>Subtotal</th>
				<th>Modificar</th>
			</thead>
			<tbody>
					<% @cart.line_items.each do |item| %>
					<tr>
						<td class="thumb">
							<% unless item.post.pictures.empty? %>
								<div class="th">
									<%= image_tag item.post.pictures.first.image.url(:thumbnail), size: "50" %>
								</div>
							<% else %>
								<p>N/A</p>
							<% end %>
						</td>
						<td><%= item.post.title %></td>
						<td>$<%= item.post.price %></td>
						<td><%= item.quantity %></td>
						<% if item.post.category == "zapato" %>
							<td><%= item.property.humanize %>, <%= item.post.gender %></td>

						<% else %>
							<td><%= item.property.humanize %>, <%= item.property_2 %></td>
						<% end %>
						<td>$<%= item.total_price_line %></td>
						<td class="edit-s">
							<%= link_to "", increase_line_item_path(item), method: :put, remote: true, class: "cart-plus fa fa-plus" %>
							<%= link_to "", decrease_line_item_path(item), method: :put, remote: true, class: "cart-minus fa fa-minus" %>
						<%= link_to "x", item, method: :delete, data: {confirm: "Estas seguro?"}, class: "button red tiny" %></td>
					</tr>
					<% end %>
					
			</tbody>
		</table>

app/views/charges/_form_oxxo.html.erb
<%= form_for(@charge, url: oxxo_create_charges_path, html: {id: 'card-form2'}) do |f| %>
  
  <div class="title text-center ">
    <%= image_tag('logo-oxxo.png', size: '120', class: "oxxo") %>
    <h1>Datos de envío</h1>
    <p>Asegurate de llenar todos los campos correctamente antes de generar el pago.</p><br><br><br>

  </div>

  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div id="panel-envio">


  <div class="large-6 medium-6 columns">
    <%= f.text_field :name, placeholder: "nombre completo", class: "", required: true %>
  </div>
  <div class="large-6 medium-6 columns">
    <%= f.text_field :phone_number, placeholder: "numero de telefono", maxlength: "10", class: "", required: true %>
  </div>

  <div class="large-12 columns">
    <%= f.text_area :full_address, placeholder: "direccion completa", class: "", required: true %>
  </div>

  <div class="large-12 columns">
    <%= f.text_field :country, placeholder: "pais", class: "", readonly: true, value: "México" %>
  </div>

  <div class="large-3 medium-3 columns">
    <%= f.text_field :state, placeholder: "estado", class: "", required: true %>
  </div>
  <div class="large-3 medium-3 columns">
    <%= f.text_field :city, placeholder: "ciudad", class: "", required: true %>
  </div>
  <div class="large-3 medium-3 columns">
    <%= f.text_field :zip_code, placeholder: "codigo postal", class: "", maxlength: "5", required: true %>
  </div>
  <div class="large-3 medium-3 columns">
    <%= f.text_field :colonia, placeholder: "colonia", class: "", required: true %>
  </div>
  
</div>





  <div class="large-6 medium-6 small-11 center">
    <%= f.button "Generar pago", class: "button small green expand pay-button radius", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>"} %>
  </div>
<% end %>

app/views/charges/cart.html.erb
<%= render 'shared/header' %>

<div class="row medium-11 small-11">
	<div class="center text-center panel-cart1">
		<div id="cart-resume">
				<%= render 'cart_resume' %>
		</div>
		<div class="large-11 medium-11 small-11 center c-field">
			<h3 class="inline left">Subtotal</h3>
			<p class="inline right">$ <%= @cart.total_price_cart %> MXN</p>
		</div>
		<div class="large-11 medium-11 small-11 center c-field">
			<h3 class="inline left">Envio</h3>
			<p class="inline right">*$ <%= @ship_price %> MXN</p>
		</div>
		<div class="large-11 medium-11 small-11 center c-field">
			<h3 class="inline left total-h3">Total</h3>
			<p class="inline right total-p">$ <%= @cart.total_price_cart + @ship_price %> MXN</p>
		</div><br><br>
		<div class="large-11 medium-11 small-11 center">
			<%= link_to "actualizar precios", cart_charges_path, class: "button green small expand" %>
			<%= link_to "eliminar todo el carrito", @cart, method: :delete, data: {confirm: 'Estas seguro de eliminar todo el carrito?'}, class: "expand" %>
		</div>

		<div class="large-11 medium-11 small-11 center text-center c-field">
				<a href="<%= new_charge_path %>" data-no-turbolink class="large-6 medium-12 small-12">
					<div class="field-rr">
						<h3>pagar con tarjeta</h3>
						<%= image_tag 'cards.png', size: '400', class: "inline" %>
					</div>
				</a><!--
			--><a href="<%= oxxo_charges_path %>" data-no-turbolink class="large-6 medium-12 small-12">
					<div class="field-rr">
						<h3>pagar con </h3>
						<%= image_tag 'logo-oxxo.png', size: '130' %>
					</div>
				</a><!-- -->
		</div>
		<div class="large-11 medium-11 small-11 center text-center">
			<p>* El costo de envio se calcula de la siguiente manera: $<%= SHIP_PRICE %> pesos por cada 2 productos.</p>
		</div>
	</div>

</div>

app/views/charges/edit.html.erb
<%= render 'ship_number' %>

app/views/charges/index.html.erb
<%= render 'admin/admin_nav' %>
<section class="content">
  <br>
  <div class="hu">
    <p><%= @charges.count %></p>
    <h2>Cargos</h2>
  </div>



  <%= search_form_for(@st, url: admin_charges_path, html:{class: "large-12"}) do |f| %>
    <%= f.search_field :user_email_or_payment_type_or_city_or_state_or_conekta_id_cont, {placeholder: "buscar email, tipo de pago, ciudad, estado o codigo de referencia", class: "radius"} %>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>produccion?</th>
        <th><%= sort_link @st, :payment_type, 'Tipo de pago' %></th>
        <th><%= sort_link @st, :amount, 'Cantidad' %></th>
        <th><%= sort_link @st, :conekta_status, 'Estado del pago en conekta' %></th>
        <th><%= sort_link @st, :created_at, 'Fecha' %></th>
        <th><%= sort_link @st, :user_email, 'Email' %></th>
        <th><%= sort_link @st, :status, 'Estado del envio' %></th>
        <th><%= sort_link @st, :ship_number, 'Numero de rastreo' %></th>

        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @charges.each do |charge| %>
        <tr>
          <% if charge.livemode == "f" %>
            <td class="text-center"><i class="fa fa-circle-o"></i></td>
          <% else %>
            <td class="text-center"><i class="fa fa-circle"></i></td>
          <% end %>

          <td class="text-center">
            <% if charge.payment_type == "OXXO" %>
              <%= image_tag('logo-oxxo.png', size: "30") %>
            <% else %>
              <i class="fa fa-cc-visa"></i>
            <% end %>
          </td>

          <td class="">$ <b><%= charge.amount %>.00</b></td>


          <% if charge.conekta_status == "paid" %>
            <td class="text-green"><b>Pagado</b></td>
          <% elsif charge.payment_type == "OXXO" %>
            <% if charge.status == "enviado" or charge.status == "listo_para_envio" or charge.status == "pago_recibido" %>
              <td class="text-green">
                <b>Pagado</b>
              </td>
            <% else %>
              <td class="text-red"><%= charge.conekta_status.humanize %></td>
            <% end %>
          <% end %>


          <td><%= local_time(charge.created_at, '%m/%e/%y %I:%M%P') %></td>
          <td><%= charge.user.try(:email) %></td>
          <td><%= charge.status.to_s.humanize %></td>

          <% if charge.ship_number.to_s.length == 0 %>
            <!-- <td><%= charge.ship_number %></td> -->
            <td class="text-center"><i class="fa fa-close"></i></td>
          <% else %>
            <td class="text-center"><i class="fa fa-check"></i></td>
          <% end %>

          
          
          <td><%= link_to 'Ver', charge %></td>
          <td><%= link_to 'Editar', edit_charge_path(charge) %></td>
          <% if can? :destroy, Charge %>
            <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= will_paginate @charges, page_links: false %>

</section>

app/views/charges/new.html.erb
<%= render 'shared/header' %>


<div class="row medium-12 small-12">

	<div class="center text-center panel-cart radius small-11">

		<div class="">
			<h1 class="">Pago con tarjeta de crédito</h1>
		</div>
	
		<div class="large-11 medium-11 small-12 center c-field">
			<h3 class="inline left">Subtotal</h3>
			<p class="inline right">$ <%= @cart.total_price_cart %> MXN</p>
		</div>
		<div class="large-11 medium-11 small-12 center c-field">
			<h3 class="inline left">Envio</h3>
			<p class="inline right">$ <%= @ship_price %>.0 MXN</p>
		</div>
		<div class="large-11 medium-11 small-12 center c-field">
			<h3 class="inline left total-h3">Total</h3>
			<p class="inline right total-p">
				$ <%= @total_price %> MXN
			</p>
		</div>

		<hr>



		<div class="large-11 center">
					<%= render 'form' %>
		</div>
	</div>

</div>

app/views/charges/oxxo.html.erb
<%= render 'shared/header' %>


<div class="row medium-12 small-12 wp1">
	<div class="m-up center panel-cart radius small-11">
		<div class="large-11 medium-11 small-12 center c-field">
			<h3 class="inline left">Subtotal</h3>
			<p class="inline right">$ <%= @cart.total_price_cart %> MXN</p>
		</div>
		<div class="large-11 medium-11 small-12 center c-field">
			<h3 class="inline left">Envio</h3>
			<p class="inline right">$ <%= @ship_price %>.0 MXN</p>
		</div>
		<div class="large-11 medium-11 small-12 center c-field">
			<h3 class="inline left total-h3">Total</h3>
			<p class="inline right total-p">
				$ <%= @total_price %> MXN
			</p>
		</div>

		<hr>



		<div class="large-11 center">
					<%= render 'form_oxxo' %>
		</div>
	</div>

</div>

app/views/charges/show.html.erb
<%= render partial: 'admin/admin_nav' %>


<section class="content">


  <div class="panel radius">

    <h3>Detalles del cargo</h3>
    <p>
      <b>Producción?:</b>
      <% if @charge.livemode == "f" %>
        <span class="text-red">no</span>
      <% else %>
        <span class="text-green">si</span>
      <% end %>
    </p><br><br>
    <p>
      <b>Cantidad:</b>
      <span class="text-green">$ <%= @charge.amount %> (incluido envío)</span>
    </p>
    <p><b>Costo envio:</b>$ <%= SHIP_PRICE %> (costo por guia)</p>

    <p>
      <b>Moneda:</b>
      <%= @charge.currency %>
    </p>
    <p>
      <b>Tipo de cargo:</b>
      <% if @charge.payment_type == "OXXO" %>
        <%= image_tag('logo-oxxo.png', size: "40") %>
      <% else %>
        <i class="fa fa-credit-card"></i>
        <%= @charge.payment_type %>
      <% end %>
    </p>
    <p>
      <b>Fecha de creación:</b>
      <%= local_time(@charge.created_at, '%m/%e/%y %I:%M%P') %>
    </p><br>
    <p>
      <b>Código de referencia:</b>
      <%= @charge.conekta_id %>
    </p><br><br>

    <% if @charge.payment_type == "OXXO" %>
      <p>
        <%= image_tag(@charge.payment_bar_url) %><br>
        <%= @charge.payment_barcode %>
      </p><br><br>
    <% end %>


    <table>
      <thead>
        <b>Productos comprados</b><br><br>
        <tr>
          <th></th>
          <th>sku</th>
          <th>nombre</th>
          <th>precio unidad</th>
          <th>cantidad</th>
          <th>propiedades</th>
          <th>subtotal</th>
        </tr>
      </thead>
      <tbody>
        <% @charge.line_items.each do |item| %>
          <tr>
            <td>
              <% unless item.post.pictures.empty? %>
                <div class="th">
                  <%= image_tag item.post.pictures.first.image.url(:thumbnail), size: "50" %>
                </div>
              <% else %>
                <p>N/A</p>
              <% end %>
            </td>
            <td><%= item.post.sku %></td>
            <td><%= item.post.title %></td>
            <td>$<%= item.post.price %></td>
            <td>x<%= item.quantity %></td>
            <% if item.property == "default" %>
              <td></td>
            <% else %>
              <td><%= item.property.humanize %>, <%= item.property_2 %></td>
            <% end %>
            <td>$<%= item.total_price_line %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br><br><br>


    <p>
      <b>Estado del pago:</b>
        <% if @charge.conekta_status == "paid" %>
          <span class="text-green">Pagado</span>
        <% elsif @charge.payment_type == "OXXO" %>
          <% if @charge.status == "enviado" or @charge.status == "listo_para_envio" or @charge.status == "pago_recibido" %>
            <span class="text-green">
              Pagado
            </span>
          <% else %>
            <span class="text-red"><%= @charge.conekta_status.humanize %></span>
          <% end %>
        <% end %>
    </p>
    <p>
      <b>Numero de rastreo:</b>
      <% if @charge.ship_number %>
        <%= @charge.ship_number %>
        <%= link_to "enviar numero de guia", send_number_charge_path(@charge), class: "inline button tiny green radius", method: :put, data: {confirm: "Estas seguro de enviar el numero de guia?, ya lo has enviado #{ @charge.counter ? @charge.counter : 0 } veces"} %>
      <% else %>
        <span class="text-red">
          <i class="fa fa-close"></i> aún no proporcionado
        </span>
      <% end %>
    </p>

  
    <p>
      <b>Estado del envío:</b>
      <%= @charge.status.humanize %>
    </p>
    
  </div>

  <div class="panel radius">
    <h3>Detalles del envío</h3>
    <p>
      <b>País:</b>
      <%= @charge.country %>
    </p>
    <p>
      <b>Estado:</b>
      <%= @charge.state %>
    </p>
    <p>
      <b>Ciudad:</b>
      <%= @charge.city %>
    </p>
    <p>
      <b>Colonia:</b>
      <%= @charge.colonia %>
    </p>
    <p>
      <b>Código postal:</b>
      <%= @charge.zip_code %>
    </p>
    <p>
      <b>Direccion completa:</b>
      <%= @charge.full_address %>
    </p>
    <p>
      <b>Nombre envío:</b>
      <%= @charge.name %>
    </p>
    <p>
      <b>Telefono:</b>
      <%= @charge.phone_number %>
    </p>
    <p>
      <b>Servicio de envío:</b>
      <%= @charge.delivery_service %>
    </p>
  </div>
  <div class="panel radius">
    <h3>Detalles del usuario</h3>
    <p>
      <b>Nombre:</b>
      <%= @charge.user.try(:name) %>
    </p>
    <p>
      <b>Email:</b>
      <%= @charge.user.try(:email) %>
    </p>
    
  </div>



  
  <%= link_to 'Editar', edit_charge_path(@charge), class: "button green tiny expand radius" %>

</section>